### Datasource info
spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/database/h2-data/backup/h2-data-backup;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/database/liquibase/changelog/changelog-master.xml
  h2:
    console:
      enabled: true


#No auth  protected
endpoints:
  shutdown:
    sensitive: false
    enabled: false